name: Run Unit tests

on: [push]

jobs:
  run-unit-test:
    name: run unit test
    runs-on: ubuntu-latest

    steps:
      uses: actions/checkout@v3
      uses: action/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
      run: npm ci
      run: npm run test
